c:
	gcc -o db 20CS10079_DBMS_Assgn3_C.c -I/usr/include/postgresql/ -lpq -o db
	./db

java:
	javac 20CS10079_DBMS_Assgn3_Java.java
	java -cp postgresql-42.5.1.jar: Yashraj_20CS10079_DBMS_Assgn3_Java

python:
	python3 20CS10079_DBMS_Assgn3_Python.py

clean:
	rm -f db
	rm -f *.class